// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1d9BGMgNVzFVwLzy6RRSLoWRED-PbQw4',
    appId: '1:32781694040:web:1fa7f2b826ef02a892862d',
    messagingSenderId: '32781694040',
    projectId: 'flutter-db-2e545',
    authDomain: 'flutter-db-2e545.firebaseapp.com',
    storageBucket: 'flutter-db-2e545.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO20nPZVLAjKCHohNEgQpKFSm3obA92fE',
    appId: '1:32781694040:android:0ddebc561030094c92862d',
    messagingSenderId: '32781694040',
    projectId: 'flutter-db-2e545',
    storageBucket: 'flutter-db-2e545.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2mvNJ4XVEt0yVOqFfvLWp_0Prw6tBmIg',
    appId: '1:32781694040:ios:b37640b2672cf8a692862d',
    messagingSenderId: '32781694040',
    projectId: 'flutter-db-2e545',
    storageBucket: 'flutter-db-2e545.appspot.com',
    iosBundleId: 'com.example.saver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2mvNJ4XVEt0yVOqFfvLWp_0Prw6tBmIg',
    appId: '1:32781694040:ios:bca7d553589b08f092862d',
    messagingSenderId: '32781694040',
    projectId: 'flutter-db-2e545',
    storageBucket: 'flutter-db-2e545.appspot.com',
    iosBundleId: 'com.example.saver.RunnerTests',
  );
}
